const express=require('express');const db=require('../services/database');const {authenticate,authorize}=require('../middleware/auth');const router=express.Router();router.use(authenticate,authorize('admin'));
router.get('/stats',async(req,res)=>{try{const q=await Promise.all([db.query('SELECT COUNT(*)::int n FROM users'),db.query("SELECT COUNT(*)::int n FROM users WHERE role='shop'"),db.query('SELECT COUNT(*)::int n FROM shops WHERE is_approved=false'),db.query("SELECT COUNT(*)::int n FROM quotes WHERE status IN ('open','bidding')")]);res.json({total_users:q[0].rows[0].n,total_shops:q[1].rows[0].n,pending_shops:q[2].rows[0].n,active_quotes:q[3].rows[0].n});}catch(e){console.error(e);res.status(500).json({error:'통계를 불러오지 못했습니다.'});}});
router.get('/users',async(req,res)=>{try{const r=await db.query('SELECT id,email,name,phone,role,created_at FROM users ORDER BY created_at DESC LIMIT 200');res.json({users:r.rows});}catch(e){res.status(500).json({error:'회원 목록을 불러오지 못했습니다.'});}});
router.get('/shops',async(req,res)=>{try{const r=await db.query('SELECT s.*,u.email,u.name FROM shops s JOIN users u ON u.id=s.user_id ORDER BY s.is_approved ASC,s.created_at DESC');res.json({shops:r.rows});}catch(e){res.status(500).json({error:'업체 목록을 불러오지 못했습니다.'});}});
router.patch('/shops/:id/approval',async(req,res)=>{try{const approved=!!req.body.approved;const r=await db.query('UPDATE shops SET is_approved=$1,updated_at=NOW() WHERE id=$2 RETURNING *',[approved,req.params.id]);if(!r.rows.length)return res.status(404).json({error:'업체를 찾을 수 없습니다.'});res.json({shop:r.rows[0],message:approved?'업체를 승인했습니다.':'업체 승인을 취소했습니다.'});}catch(e){res.status(500).json({error:'업체 상태 변경 실패'});}});
router.patch('/shops/:id/active',async(req,res)=>{try{const active=!!req.body.active;const r=await db.query('UPDATE shops SET is_active=$1,updated_at=NOW() WHERE id=$2 RETURNING *',[active,req.params.id]);if(!r.rows.length)return res.status(404).json({error:'업체를 찾을 수 없습니다.'});res.json({shop:r.rows[0]});}catch(e){res.status(500).json({error:'업체 상태 변경 실패'});}});
router.patch('/users/:id/role',async(req,res)=>{try{const role=req.body.role;if(!['user','shop','admin'].includes(role))return res.status(400).json({error:'잘못된 권한입니다.'});if(req.params.id===req.user.id&&role!=='admin')return res.status(400).json({error:'자신의 관리자 권한은 여기서 변경할 수 없습니다.'});const r=await db.query('UPDATE users SET role=$1,updated_at=NOW() WHERE id=$2 RETURNING id,email,name,role',[role,req.params.id]);if(!r.rows.length)return res.status(404).json({error:'회원을 찾을 수 없습니다.'});res.json({user:r.rows[0]});}catch(e){res.status(500).json({error:'권한 변경 실패'});}});
// 최고 관리자의 회원 삭제. 본인 또는 다른 최고 관리자는 실수로 삭제할 수 없게 보호합니다.
router.delete('/users/:id',async(req,res)=>{try{if(req.params.id===req.user.id)return res.status(400).json({error:'현재 로그인한 최고 관리자 계정은 삭제할 수 없습니다.'});const client=await db.pool.connect();try{await client.query('BEGIN');const found=await client.query('SELECT id,role FROM users WHERE id=$1 FOR UPDATE',[req.params.id]);if(!found.rows.length){await client.query('ROLLBACK');return res.status(404).json({error:'회원을 찾을 수 없습니다.'});}if(found.rows[0].role==='admin'){await client.query('ROLLBACK');return res.status(400).json({error:'다른 최고 관리자 계정은 여기서 삭제할 수 없습니다.'});}await client.query('DELETE FROM users WHERE id=$1',[req.params.id]);await client.query('COMMIT');res.json({message:'회원과 연결된 업체 정보가 삭제되었습니다.'});}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}catch(e){console.error('회원 삭제 실패:',e);res.status(500).json({error:'회원 삭제에 실패했습니다. 연결된 데이터가 있어 삭제할 수 없는 경우 데이터 관계를 먼저 확인해주세요.'});}});
router.delete('/shops/:id',async(req,res)=>{try{const r=await db.query('SELECT user_id FROM shops WHERE id=$1',[req.params.id]);if(!r.rows.length)return res.status(404).json({error:'업체를 찾을 수 없습니다.'});req.params.id=r.rows[0].user_id;return router.handle({...req,url:'/users/'+req.params.id,method:'DELETE'},res);}catch(e){res.status(500).json({error:'업체 삭제 실패'});}});
module.exports=router;