const express=require('express');const fs=require('fs');const path=require('path');const db=require('../services/database');const {authenticate,authorize}=require('../middleware/auth');const router=express.Router();
const uploadDir=path.join(__dirname,'..','public','uploads','generated');if(!fs.existsSync(uploadDir))fs.mkdirSync(uploadDir,{recursive:true});
const presets={menu:{prefix:'premium Korean PC service app illustration, clean modern 3D, MYCOM brand style, technology, friendly, no text, no watermark'},ai:{prefix:'friendly Korean AI computer consultant assistant illustration, premium modern 3D, trustworthy, warm, no text, no watermark'},shop:{prefix:'professional Korean computer shop storefront and custom PC showroom, bright realistic marketing image, no people, no text, no watermark'},banner:{prefix:'premium promotional banner for Korean computer service platform MYCOM, modern technology, dynamic composition, empty safe area for headline text, no watermark'}};
function buildPrompt(category,prompt){return `${presets[category]?.prefix||presets.menu.prefix}, ${String(prompt||'computer service').slice(0,1200)}`}
router.get('/',async(req,res)=>{try{const r=await db.query('SELECT id,category,title,prompt,image_url,provider,created_at FROM generated_images WHERE is_active=true ORDER BY created_at DESC LIMIT 100');res.json({images:r.rows});}catch(e){res.status(500).json({error:'이미지 목록을 불러오지 못했습니다.'})}});
router.get('/featured/:category',async(req,res)=>{try{const r=await db.query('SELECT id,category,title,image_url FROM generated_images WHERE category=$1 AND is_active=true ORDER BY created_at DESC LIMIT 1',[req.params.category]);res.json({image:r.rows[0]||null});}catch(e){res.status(500).json({error:'이미지를 불러오지 못했습니다.'})}});
router.post('/generate',authenticate,authorize('admin'),async(req,res)=>{try{if(!process.env.NOVELAI_API_TOKEN)return res.status(503).json({error:'NOVELAI_API_TOKEN이 설정되지 않았습니다. Render 환경변수에 API 토큰을 추가해주세요.'});const {category='menu',title='',prompt='',width=1024,height=1024,steps=28}=req.body;if(!presets[category])return res.status(400).json({error:'지원하지 않는 이미지 종류입니다.'});const fullPrompt=buildPrompt(category,prompt);const payload={input:fullPrompt,model:'nai-diffusion-4-5-full',action:'generate',parameters:{width:Number(width)||1024,height:Number(height)||1024,scale:6.5,sampler:'k_euler_ancestral',steps:Math.min(Math.max(Number(steps)||28,10),50),n_samples:1,uc:'text, watermark, logo, blurry, low quality, distorted'}};
const r=await fetch('https://image.novelai.net/ai/generate-image',{method:'POST',headers:{'Authorization':'Bearer '+process.env.NOVELAI_API_TOKEN,'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(payload)});if(!r.ok){const detail=(await r.text()).slice(0,500);return res.status(502).json({error:'NovelAI 이미지 생성에 실패했습니다.',detail});}const data=await r.json();let base64=data?.image||data?.images?.[0]?.image||data?.output?.[0];if(!base64)return res.status(502).json({error:'NovelAI 응답에서 이미지를 찾지 못했습니다.'});base64=base64.replace(/^data:image\/\w+;base64,/,'');const filename=`mycom-${category}-${Date.now()}-${Math.random().toString(36).slice(2,8)}.png`;fs.writeFileSync(path.join(uploadDir,filename),Buffer.from(base64,'base64'));const image_url='/uploads/generated/'+filename;const saved=await db.query('INSERT INTO generated_images(category,title,prompt,image_url,provider,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[category,title||category,fullPrompt,image_url,'novelai',req.user.id]);res.status(201).json({image:saved.rows[0]});}catch(e){console.error('image generate',e);res.status(500).json({error:'이미지 생성 중 서버 오류가 발생했습니다.'})}});
router.patch('/:id/active',authenticate,authorize('admin'),async(req,res)=>{try{const r=await db.query('UPDATE generated_images SET is_active=$1 WHERE id=$2 RETURNING *',[!!req.body.active,req.params.id]);if(!r.rows.length)return res.status(404).json({error:'이미지를 찾을 수 없습니다.'});res.json({image:r.rows[0]});}catch(e){res.status(500).json({error:'이미지 상태 변경 실패'})}});
module.exports=router;