const express=require('express');const fs=require('fs');const path=require('path');const AdmZip=require('adm-zip');const db=require('../services/database');const {authenticate,authorize}=require('../middleware/auth');const router=express.Router();
const uploadDir=path.join(__dirname,'..','public','uploads','generated');if(!fs.existsSync(uploadDir))fs.mkdirSync(uploadDir,{recursive:true});
const presets={menu:{prefix:'premium Korean PC service app illustration, clean modern 3D editorial art, warm studio lighting, friendly, premium, simple composition, no text, no letters, no watermark'},ai:{prefix:'friendly Korean AI computer consultant assistant, premium modern 3D illustration, trustworthy, warm, helpful technology atmosphere, no text, no watermark'},shop:{prefix:'professional Korean computer service store and custom PC showroom, bright premium realistic marketing photography, clean organized interior, no people, no text, no watermark'},banner:{prefix:'premium Korean technology service campaign banner, modern editorial composition, dynamic but clean, subject on right side, generous empty safe area on left for MYCOM headline overlay, no text, no watermark'}};
const starter=[
 ['menu','컴퓨터 견적','premium custom gaming PC with subtle RGB, premium desk setup, approachable modern 3D illustration'],['menu','조립대행','expert hands carefully assembling a custom desktop PC, premium clean workshop, modern 3D illustration'],['menu','방문 예약','friendly computer technician arriving for a home PC service visit, clean Korean apartment, premium 3D illustration'],['menu','내 컴퓨터 팔기','well maintained used desktop computer ready for resale, clean studio product composition, premium 3D illustration'],['menu','PC 수리','computer repair diagnostics with open desktop and tools, clean modern service workshop, premium 3D illustration'],['menu','가까운 업체','modern Korean computer store exterior with glowing custom PCs visible inside, friendly neighborhood technology service, premium illustration'],
 ['ai','MYCOM AI 상담사','friendly futuristic AI computer consultant with soft green accents, laptop and PC components, warm approachable expression, premium 3D character illustration'],
 ['shop','기본 매장 이미지','bright professional Korean computer showroom, custom gaming PCs and service counter, trustworthy and clean'],
 ['banner','내 PC, 더 쉽게 해결하세요','premium custom PC floating above subtle green technology landscape, clean modern Korean service campaign, subject right, empty left area'],['banner','가까운 전문가와 바로 연결','friendly local computer expert and premium desktop setup, clean campaign image, subject right, empty left area']
];
function buildPrompt(category,prompt){return `${presets[category]?.prefix||presets.menu.prefix}, ${String(prompt||'computer service').slice(0,1200)}`}
async function generate(category,title,prompt,userId){if(!process.env.NOVELAI_API_TOKEN)throw new Error('NOVELAI_API_TOKEN이 설정되지 않았습니다.');if(!presets[category])throw new Error('지원하지 않는 이미지 종류입니다.');const fullPrompt=buildPrompt(category,prompt);const payload={input:fullPrompt,model:'nai-diffusion-4-5-full',action:'generate',parameters:{width:category==='banner'?1536:1024,height:category==='banner'?768:1024,scale:6.5,sampler:'k_euler_ancestral',steps:28,n_samples:1,uc:'text, letters, watermark, logo, blurry, low quality, distorted, duplicate'}};
const r=await fetch('https://image.novelai.net/ai/generate-image',{method:'POST',headers:{Authorization:'Bearer '+process.env.NOVELAI_API_TOKEN,'Content-Type':'application/json','Accept':'application/json, application/octet-stream'},body:JSON.stringify(payload)});if(!r.ok)throw new Error('NovelAI 오류: '+(await r.text()).slice(0,500));const type=r.headers.get('content-type')||'';let buf,ext='png';if(type.includes('application/json')){const data=await r.json();let b=data?.image||data?.images?.[0]?.image||data?.output?.[0];if(!b)throw new Error('NovelAI 응답에서 이미지를 찾지 못했습니다.');buf=Buffer.from(String(b).replace(/^data:image\/\w+;base64,/,''),'base64')}else{const raw=Buffer.from(await r.arrayBuffer());if(raw.subarray(0,2).toString()==='PK'){const zip=new AdmZip(raw);const entry=zip.getEntries().find(x=>/\.(png|webp|jpg|jpeg)$/i.test(x.entryName));if(!entry)throw new Error('NovelAI ZIP 응답에서 이미지 파일을 찾지 못했습니다.');buf=entry.getData();ext=path.extname(entry.entryName).slice(1)||'png'}else{buf=raw;if(type.includes('webp'))ext='webp';if(type.includes('jpeg'))ext='jpg'}}
const filename=`mycom-${category}-${Date.now()}-${Math.random().toString(36).slice(2,8)}.${ext}`;fs.writeFileSync(path.join(uploadDir,filename),buf);const image_url='/uploads/generated/'+filename;const saved=await db.query('INSERT INTO generated_images(category,title,prompt,image_url,provider,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[category,title||category,fullPrompt,image_url,'novelai',userId]);return saved.rows[0]}
router.get('/',async(req,res)=>{try{const r=await db.query('SELECT id,category,title,prompt,image_url,provider,created_at FROM generated_images WHERE is_active=true ORDER BY created_at DESC LIMIT 100');res.json({images:r.rows})}catch(e){res.status(500).json({error:'이미지 목록을 불러오지 못했습니다.'})}});
router.get('/featured/:category',async(req,res)=>{try{const r=await db.query('SELECT id,category,title,image_url FROM generated_images WHERE category=$1 AND is_active=true ORDER BY created_at DESC LIMIT 30',[req.params.category]);res.json({image:r.rows[0]||null,images:r.rows})}catch(e){res.status(500).json({error:'이미지를 불러오지 못했습니다.'})}});
router.post('/generate',authenticate,authorize('admin'),async(req,res)=>{try{const {category='menu',title='',prompt=''}=req.body;const image=await generate(category,title,prompt,req.user.id);res.status(201).json({image})}catch(e){console.error('image generate',e);res.status(502).json({error:e.message||'이미지 생성 실패'})}});
router.post('/starter-pack',authenticate,authorize('admin'),async(req,res)=>{try{const existing=await db.query('SELECT category,title FROM generated_images WHERE is_active=true');const keys=new Set(existing.rows.map(x=>x.category+'|'+x.title));const jobs=starter.filter(x=>!keys.has(x[0]+'|'+x[1]));if(!jobs.length)return res.json({created:[],message:'기본 이미지가 이미 준비되어 있습니다.'});const created=[];for(const [category,title,prompt] of jobs){try{created.push(await generate(category,title,prompt,req.user.id))}catch(e){console.error('starter image failed',title,e.message)}}res.status(201).json({created,message:`${created.length}개의 MYCOM 기본 이미지를 생성했습니다.`})}catch(e){res.status(502).json({error:e.message||'기본 이미지 생성 실패'})}});
router.patch('/:id/active',authenticate,authorize('admin'),async(req,res)=>{try{const r=await db.query('UPDATE generated_images SET is_active=$1 WHERE id=$2 RETURNING *',[!!req.body.active,req.params.id]);if(!r.rows.length)return res.status(404).json({error:'이미지를 찾을 수 없습니다.'});res.json({image:r.rows[0]})}catch(e){res.status(500).json({error:'이미지 상태 변경 실패'})}});
module.exports=router;